# Generated by Django 3.1.1 on 2022-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_music', '0002_categoria_marca_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
