# Generated by Django 3.1.1 on 2022-04-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_music', '0003_auto_20220422_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=500, unique=True)),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_music.categoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_music.modelo')),
            ],
        ),
    ]
